import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ConvexClientProvider } from "@/lib/provider/ConvexClientProvider";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "sonner";
import { dark } from "@clerk/themes";
import { QueryProvider } from "@/lib/provider/QueryProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryProvider>
          <ClerkProvider
            appearance={{
              theme: dark,
            }}
          >
            <body
              className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
              <ConvexClientProvider>
                <main>{children}</main>
              </ConvexClientProvider>
              <Toaster />
            </body>
          </ClerkProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
